### ISSUE TITLE
functorch merge with pytorch

### ISSUE THREAD

**Issue by awvwgk** [conda-forge/pytorch-cpu-feedstock#148]
### Comment:

With version 1.13 the functorch package has been merged into pytorch, see https://github.com/pytorch/functorch/releases/tag/v1.13.0. The functorch package is replaced by an empty package depending on pytorch.

This could be provided by this feedstock as well by an additional functorch output.

**Comment by awvwgk** [comment]
I was thinking about providing a separate output like

````yaml
{% if linux and x86_64 %}
  - name: functorch

    build:
      noarch: generic

    requirements:
      run:
        - pytorch {{ version }}

    test:
      imports:
        - functorch
{% endif %}
````

To ensure environments currently depending on functorch can easily upgrade. The functorch feedstock should probably be archived by the core team afterwards.
