### ISSUE TITLE
Slow/unstable inference on OSX ARM64

### ISSUE THREAD

**Issue by wietsedv** [conda-forge/pytorch-cpu-feedstock#38]
I wanted to use PyTorch for inference on my ARM64 Mac and I managed through trial and error to make a working conda recipe for PyTorch that I build locally on my Mac before I noticed that there now is a working ARM64 build on conda-forge.

When I compared my local build with the one of conda-forge, I found that my local build is much faster at Wav2Vec2 inference while using less resources. Additionally, the conda-forge build breaks at a certain point for no appearant reason. I test both builds in the exact same conda environment (Python 3.8.8).

Conda-forge build:

    /opt/mambaforge/envs/testenv/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown

Local build: 200% CPU, 4.9GB memory, 2,8 seconds per iteration on average
Conda-forge build: 600% CPU, 4,4GB memory, 6.6 s/it

My build is nonstandard since I disabled some requirements / features just to make it build. I do not have the time/skill right now to completely investigate the problem, but I may look into it later.

meta.yaml:
```yaml
{% set name = "pytorch" %}
{% set version = "1.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/pytorch/pytorch.git
  git_rev: "v{{ version }}"
  git_depth: 1

requirements:
  host:
    - numpy >=1.12
    - pip
    - python
    # - ninja
    - pyyaml
    # - mkl
    # - mkl-include
    - setuptools
    - cmake
    - cffi
    - typing_extensions
    - future
    - six
    - requests
    - dataclasses
  run:
    - numpy >=1.12
    - python
    # - libopenblas
    - cffi
    - typing_extensions
    - future
    - six
    - requests
    - dataclasses

test:
  imports:
    - torch
```

build.sh:
```bash
git submodule update --init --recursive

export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}

MACOSX_DEPLOYMENT_TARGET=11.0 CC=clang CXX=clang++ MAX_JOBS=$CPU_COUNT BUILD_TEST=0 USE_MKLDNN=0 USE_OPENMP=0 $PYTHON setup.py install
```

Building this on a M1 Macbook Pro takes about 45 minutes. I uploaded my build to anaconda if someone wants to use/test it without building yourself: https://anaconda.org/wietsedv/pytorch/files
